import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react';
import 'antd/dist/antd.css';
import { Layout, Button, Tag } from 'antd';
import { database } from '../firebase'
import MainHeader from '../components/MainHeader';
import CardGallery from '../components/CardGallery';

const { Content } = Layout;

export const Home = () => {
  const [items, setItems] = useState([])

  useEffect(() => {
    if (database) {
      let initialItems = [
        {
          name: `Brennan's Winery`,
          featured_image: '/1.jpeg',
          neighborhood: 'Comanche',
        },
        {
          name: `Lucky Vines`,
          featured_image: '/2.jpeg',
          neighborhood: 'Comanche',
        },
        {
          name: `Cockerell Vineyards`,
          featured_image: '/3.jpeg',
          neighborhood: 'Comanche',
        }
      ]
      setItems(initialItems)
    }
  }, [])
  return (
    <>
      <Head>
        <title>The Texas Winery Passport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout">
        <MainHeader />
        <Content
          style={{
            background: '#ffffff'
          }}
        >
          <div className={styles.container}>
            <h1 className={styles.pageHeader}>Nearby Wineries</h1>
            <p>{items.length} wineries within <Tag color="green">15 miles</Tag> of 76224</p>
            <CardGallery items={items} />
          </div>
          <ShowMap />
        </Content>
      </Layout>

      <main className={styles.main}>

      </main>
    </>
  )
}

const ShowMap = () => {
  return (
    <div className={styles.showMap}>
      <Button className={styles.antBtn} type="primary">Show Map</Button>
    </div>
  )
}

export default Home;
